export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
export const SUCCESS_LOADING_EVENTS = "SUCCESS_LOADING_EVENTS";
export const LOAD_EVENT_SUCCESS = "LOAD_EVENT_SUCCESS";
export const BEGIN_LOADING_EVENTS = "BEGIN_LOADING_EVENTS";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_LOCATIONS_SUCCESS = "LOAD_LOCATIONS_SUCCESS";
export const UPDATE_SEARCHFORM = "UPDATE_SEARCHFORM";